config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
dotfiles:
  d_config_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  d_config_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_config_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  d_config_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_config_wofi:
    src: config/wofi
    dst: ~/.config/wofi
  f_config_rofimoji.rc:
    src: config/rofimoji.rc
    dst: ~/.config/rofimoji.rc
  d_config_fish:
    src: config/fish
    dst: ~/.config/fish
profiles:
  linux:
    dotfiles:
    - d_config_hypr
    - d_config_alacritty
    - d_config_swaylock
    - d_config_waybar
    - d_config_wofi
    - f_config_rofimoji.rc
    - d_config_fish
  wsl:
    dotfiles:
    - d_config_fish
