import:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml

env:
  TERM: alacritty
  LANG: "en_US.UTF-8"
  LC_CTYPE: en_US.UTF-8
  WINIT_X11_SCALE_FACTOR: "1"

window:
  opacity: 0.9
  padding:
    x: 0
    y: 0

font:
  normal:
    family: Iosevka Nerd Font
    style: Regular
  size: 12
