[Variables]
Bar_Opacity=00
Bar_Width =1920
Bar_Height =40
Bar_OffsetX =0
Bar_OffsetY =12

Section_Height =40
Section_Padding = 12

Color_Scheme1 =3B4252
Color_Scheme2 =D8DEE9
Color_Scheme3 =2E3440
Color_Scheme4 =88C0D0
Color_Scheme5 =ECEFF4

Font_Face1=PixelMPlus12
Font_Face2=Balthasar Regular NBP
Font_Size=9

Shadow=0
Translucent=0
DefaultAddedModules=startmenu,tray,music,time,date,volume,weather,netspeed

