[helpers]

[hyprland]
depends = []

[hyprland.files]
"dotfiles/hypr" = "~/.config/hypr"

[waybar.files]
"dotfiles/waybar" = "~/.config/waybar"

[swaylock]
depends = ["colors"]

[swaylock.files]
"dotfiles/swaylock" = "~/.config/swaylock"

[wofi.files]
"dotfiles/wofi" = "~/.config/wofi"

[alacritty]
depends = ["colors"]

[alacritty.files]
"dotfiles/alacritty" = "~/.config/alacritty"

[rofimoji.files]
"dotfiles/rofimoji.rc" = "~/.config/rofimoji.rc"

[fish.files]
"dotfiles/fish/config.fish" = "~/.config/fish/config.fish"
"dotfiles/fish/fish_plugins" = "~/.config/fish/fish_plugins"

[colors]