[helpers]
hex_to_rgb = ".dotter/helpers/hex_to_rgb.rhai"
hex_to_rgba = ".dotter/helpers/hex_to_rgba.rhai"

[hyprland]
depends = []

[hyprland.files]
"dotfiles/hypr" = "~/.config/hypr"

[waybar.files]
"dotfiles/waybar" = "~/.config/waybar"

[swaylock]
depends = ["colors"]

[swaylock.files]
"dotfiles/swaylock" = "~/.config/swaylock"

[wofi.files]
"dotfiles/wofi" = "~/.config/wofi"

[alacritty]
depends = ["colors"]

[alacritty.files]
"dotfiles/alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"

[rofimoji.files]
"dotfiles/rofimoji.rc" = "~/.config/rofimoji.rc"

[fish.files]
"dotfiles/fish/config.fish" = "~/.config/fish/config.fish"
"dotfiles/fish/fish_plugins" = "~/.config/fish/fish_plugins"

[mako.files]
"dotfiles/mako/config" = "~/.config/mako/config"

[nvim.files]
"dotfiles/nvim" = "~/.config/nvim"

[colors]
