includes = []
packages = ["hyprland", "swaylock", "waybar", "alacritty", "rofimoji", "wofi", "fish"]

[files]

[variables.colors]
    # Aquarim - Copied from base46 NvChad
    background = "#20202A" # base00
    foreground = "#bac0cb" # base05
    cursor = "#bac0cb" # base05
    base00 = "#20202A"
    base01 = "#2c2e3e"
    base02 = "#3D4059"
    base03 = "#313449"
    base04 = "#63718b"
    base05 = "#bac0cb"
    base06 = "#c5cbd6"
    base07 = "#ced4df"
    base08 = "#ebb9b9"
    base09 = "#e8cca7"
    base0A = "#e6dfb8"
    base0B = "#b1dba4"
    base0C = "#b8dceb"
    base0D = "#a3b8ef"
    base0E = "#f6bbe7"
    base0F = "#eAc1c1"
