# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$all[via](white) [pwsh](bold purple) 
$character"""

[line_break]
disabled = true
# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[>](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[>](bold red)" 

# Disable the package module, hiding it from the prompt completely
[directory]
truncation_length = 0
use_logical_path = false

[directory.substitutions]
"/mnt/c/Users/asus" = "ahmed"

[java]
detect_extensions = ["java", "class", "gradle", "cljs", "cljc"]
